version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://scraping_websites:scraping_websites@db/scraping_websites_dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=scraping_websites
      - POSTGRES_PASSWORD=scraping_websites
      - POSTGRES_DB=scraping_websites_dev

volumes:
  postgres_data: